<?php
// $Id: feeds_cjs_package_parser.module,v 1.1.4.1 2011/02/05 18:12:18 twistor Exp $

/**
 * Implements hook_feeds_plugins().
 */
function feeds_cjs_package_parser_feeds_plugins() {
  $info = array();
  $info['FeedsCJSPackageParser'] = array(
    'name'        => t('CommonJS Package Parser'),
    'description' => t('Parse a package.json file.'),
    'handler' => array(
      'parent' => 'FeedsParser',
      'class'  => 'FeedsCJSPackageParser',
      'file'   => 'FeedsCJSPackageParser.inc',
      'path'   => drupal_get_path('module', 'feeds_cjs_package_parser')
    ),
  );
  return $info;
}

/**
 * Implements hook_enable().
 *
 * Clear Feed's plugin cache so that this plugin shows up.
 */
function feeds_cjs_package_parser_enable() {
  cache_clear_all('plugins:feeds:plugins', 'cache');
}
